language: java

sudo: false

jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

branches:
  only:
  - master

stages:
  - compile
  - linter
  - test

jobs:
  include:
  - stage: compile
    script:
    - "./gradlew compileKotlin"

  - stage: linter
    script:
    - "./gradlew detektFormat"

  - stage: test
    script:
    - "./gradlew junitPlatformJacocoReport"
    - bash <(curl -s https://codecov.io/bash)
